name: Test && Build && Deploy
on:
  push:
    branches:
      - master
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.output-step.outputs.version }}
    steps:
      - run: |
          version="$(date +'%Y.%m.%d').${{ github.run_number }}${{ github.run_attempt }}" \
                    && echo "version=$version" >> $GITHUB_ENV
        shell: bash
      - id: output-step
        run: echo "version=$(echo presence${{ env.version }})" >> $GITHUB_OUTPUT
        shell: bash
        
  dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xt0rted/setup-dotnet@v1
        with:
          dotnet-version: 7.0.*
      - run: |
          dotnet test --collect:"XPlat Code Coverage" --results-directory ./coverage
        shell: bash
  
  docker:
    runs-on: ubuntu-latest
    needs: [init, dotnet]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: kamushekstone/presencebot:${{ needs.init.outputs.version }}
          platforms: |
            linux/arm64/v8
            linux/amd64